name: Build

on:
  workflow_dispatch:
    inputs:
      version:
        required: true
        type: string
  workflow_call:
    inputs:
      version:
        required: true
        type: string

permissions:
  contents: read

env:
  HOMEBREW_DEVELOPER: 1
  HOMEBREW_NO_AUTO_UPDATE: 1

jobs:
  build:
    strategy:
      matrix:
        runner:
          - macos-13 # intel
          - macos-14 # arm
          - ubuntu-22.04
          - ubuntu-22.04-arm
      fail-fast: false
    runs-on: ${{ matrix.runner }}
    steps:
      - uses: actions/checkout@main

      # Static gem extensions typically require the same Ruby version available already
      - uses: ruby/setup-ruby@v1
        id: setup-ruby
        with:
          ruby-version: ${{ inputs.version }}
        if: startsWith(matrix.runner, 'macos') && !startsWith(inputs.version, '3.4')

      - name: Install Homebrew
        run: |
          /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
          echo "/home/linuxbrew/.linuxbrew/bin" >> $GITHUB_PATH
          eval "$(/home/linuxbrew/.linuxbrew/bin/brew shellenv)"
          brew tap spinel-coop/rv-ruby .

      - name: Build rv Ruby
        env:
          HOMEBREW_BASERUBY: ${{ steps.setup-ruby.outputs.ruby-prefix }}/bin/ruby
        run: |
          if [[ "${{ runner.arch }}" == "ARM64" ]]; then
            export HOMEBREW_ARM64_TESTING=1
          fi
          mkdir -p bottle/
          cd bottle
          brew rv-package --verbose --with-yjit rv-ruby@${{ inputs.version }}

      - name: Upload rv Ruby
        uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4.6.2
        with:
          name: rv-ruby@${{ inputs.version }}_${{ matrix.runner }}
          path: ${{github.workspace}}/bottle

      - name: Test Portable Ruby
        run: |
          mkdir -p rv-ruby/
          tar --strip-components 2 -C rv-ruby -xf bottle/*.tar.gz
          export PATH="${PWD}/rv-ruby/bin:${PATH}"
          ruby --version --yjit
          ruby -r debug -r bigdecimal -r json -r yaml -r reline -e "true"
