name: Build

on:
  workflow_call:
  workflow_dispatch:

permissions:
  contents: read

env:
  HOMEBREW_DEVELOPER: 1
  HOMEBREW_NO_AUTO_UPDATE: 1
  HOMEBREW_ARM64_TESTING: 1

jobs:
  build:
    strategy:
      matrix:
        os: [self-hosted, ubuntu-22.04, ubuntu-22.04-arm]
        ruby: [3.4.5, 3.4.4, 3.4.3]
      fail-fast: true
    runs-on: ${{matrix.os}}
    container: ${{matrix.container && fromJSON(matrix.container) || ''}}
    defaults:
      run:
        working-directory: ${{matrix.workdir || github.workspace}}
    steps:
      - uses: actions/checkout@main
      - name: Install Homebrew
        run: |
          /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
          echo "/home/linuxbrew/.linuxbrew/bin" >> $GITHUB_PATH
          eval "$(/home/linuxbrew/.linuxbrew/bin/brew shellenv)"
          brew tap spinel-sh/rv-ruby .

      - name: Build Portable Ruby
        run: |
          mkdir -p bottle/
          cd bottle
          brew portable-package --verbose portable-ruby@${{matrix.ruby}}

      - name: Upload Portable Ruby
        uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4.6.2
        with:
          name: bottles_${{matrix.os}}
          path: ${{matrix.workdir || github.workspace}}/bottle

      - name: Test Portable Ruby
        run: |
          mkdir -p portable-ruby/
          tar --strip-components 2 -C portable-ruby -xf bottle/portable-ruby@*.tar.gz
          export PATH="${PWD}/portable-ruby/bin:${PATH}"
          export HOMEBREW_USE_RUBY_FROM_PATH=1
          rm -rf "$(brew --repo)/Library/Homebrew/vendor/portable-ruby"
          brew config | awk -v s="${PWD}/portable-ruby/bin/ruby" '$0~s{r=1} 1; END{exit(!r)}'
