name: Build

on:
  workflow_dispatch:
    inputs:
      version:
        required: true
        type: string
  workflow_call:
    inputs:
      version:
        required: true
        type: string

permissions:
  contents: read

env:
  HOMEBREW_DEVELOPER: 1
  HOMEBREW_NO_AUTO_UPDATE: 1

jobs:
  build:
    strategy:
      matrix:
        runner:
          # - macos-13 # intel
          # - macos-14 # arm
          - ubuntu-22.04
          # - ubuntu-22.04-arm
      fail-fast: false
    runs-on: ${{ matrix.runner }}
    steps:
      - uses: actions/checkout@main

      # Static gem extensions typically require the same Ruby version available already
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ inputs.version }}
        if: startsWith(matrix.runner, 'macos')

      - name: Install Homebrew
        run: |
          /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
          echo "/home/linuxbrew/.linuxbrew/bin" >> $GITHUB_PATH
          eval "$(/home/linuxbrew/.linuxbrew/bin/brew shellenv)"
          brew tap spinel-coop/rv-ruby .

      - name: Build rv Ruby
        run: |
          if [[ "${{ runner.arch }}" == "ARM64" ]]; then
            export HOMEBREW_ARM64_TESTING=1
          fi
          mkdir -p bottle/
          cd bottle
          brew portable-package --verbose --with-yjit portable-ruby@${{ inputs.version }}

      - name: Upload rv Ruby
        uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4.6.2
        with:
          name: bottles_portable-ruby@${{ inputs.version }}_${{ matrix.runner }}
          path: ${{github.workspace}}/bottle

      - name: Test Portable Ruby
        run: |
          if [[ "${{ runner.arch }}" == "ARM64" ]]; then
            export HOMEBREW_ARM64_TESTING=1
          fi
          mkdir -p portable-ruby/
          tar --strip-components 2 -C portable-ruby -xf bottle/*.tar.gz
          export PATH="${PWD}/portable-ruby/bin:${PATH}"
          export HOMEBREW_USE_RUBY_FROM_PATH=1
          rm -rf "$(brew --repo)/Library/Homebrew/vendor/portable-ruby"
          brew config | awk -v s="${PWD}/portable-ruby/bin/ruby" '$0~s{r=1} 1; END{exit(!r)}'
