name: Release

on:
  workflow_dispatch:
    inputs:
      tag:
        required: true
        default:
          # - 3.4.1
          # - 3.4.2
          # - 3.4.3
          # - 3.4.4
          - 3.4.5

env:
  HOMEBREW_DEVELOPER: 1
  HOMEBREW_NO_AUTO_UPDATE: 1

permissions:
  contents: read

jobs:
  build:
    steps:
    - uses: ./.github/workflows/build.yml
      with:
        formula: portable-ruby@${{ inputs.tag }}

  release:
    needs: build
    runs-on: ubuntu-latest
    env:
      TAG: ${{ inputs.tag }}
    permissions:
      contents: write
      packages: write
    steps:
      - uses: actions/checkout@main
      - name: Install Homebrew
        run: |
          /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
          echo "/home/linuxbrew/.linuxbrew/bin" >> $GITHUB_PATH
          eval "$(/home/linuxbrew/.linuxbrew/bin/brew shellenv)"
          brew tap spinel-coop/rv-ruby .

      - name: Checkout branch
        run: git checkout "${GITHUB_REF_NAME}"

      - name: Install gems
        run: brew install-bundler-gems --groups=pr_upload

      - name: Configure Git user
        uses: Homebrew/actions/git-user-config@main

      - name: Setup directory
        run: mkdir bottles

      - name: Download bottles
        uses: actions/download-artifact@634f93cb2916e3fdff6788551b99b062d0335ce0 # v5.0.0
        with:
          pattern: bottles_*
          path: bottles
          merge-multiple: true

      - name: Upload to GitHub Packages
        working-directory: bottles
        env:
          HOMEBREW_GITHUB_PACKAGES_USER: ${{ github.actor }}
          HOMEBREW_GITHUB_PACKAGES_TOKEN: ${{ github.token }}
        run: brew pr-upload --debug --upload-only --root-url="https://ghcr.io/v2/${GITHUB_REPOSITORY,,}"

      - name: Push tag
        env:
          GITHUB_TOKEN: ${{ github.token }}
        run: |
          gh release create "${TAG}" --notes "rv Ruby ${TAG}" --target "$(git rev-parse --verify HEAD)" --title "${TAG}"

      - name: Upload to GitHub Releases
        working-directory: bottles
        env:
          HOMEBREW_GITHUB_API_TOKEN: ${{ github.token }}
        run: brew pr-upload --debug --upload-only --root-url="https://github.com/${GITHUB_REPOSITORY}/releases/download/${TAG}"

      - name: Cleanup
        run: rm -rvf bottles
