name: CI

on:
  push:
    branches:
      - main
  pull_request:

permissions:
  contents: read

concurrency:
  group: "${{ github.ref }}"
  cancel-in-progress: ${{ github.event_name == 'pull_request' }}

jobs:
  syntax:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Homebrew
        uses: Homebrew/actions/setup-homebrew@main
      - run: brew test-bot --only-tap-syntax
   
  validate-bin-setup:
    name: "Validate that bin/setup runs successfully"
    strategy:
      matrix:
        runner:
          - macos-13 # intel
          - macos-14 # arm
          - ubuntu-22.04
          - ubuntu-22.04-arm
      fail-fast: false
    runs-on: ${{ matrix.runner }}
    steps:
      - uses: actions/checkout@main
      - name: Set up Homebrew
        run: |
          /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
          echo "/home/linuxbrew/.linuxbrew/bin" >> $GITHUB_PATH
          eval "$(/home/linuxbrew/.linuxbrew/bin/brew shellenv)"
      - name: Run bin/setup
        run: |
          bin/setup

  # list_edited_formulas:
  # build_edited_formulas:

  # build:
  #   needs: syntax
  #   if: github.event_name != 'push'
  #   uses: ./.github/workflows/build.yml
  #   with:
  #     formula: portable-ruby@3.4.5

  # This job is used as a required status check, instead of requiring each build matrix element.
  # When using ephemeral runners, the name of those runs change every time so they cannot be set as required.
  # conclusion:
  #   needs: build
  #   runs-on: ubuntu-latest
  #   if: github.event_name != 'push' && !cancelled()
  #   steps:
  #     - name: Result
  #       env:
  #         RESULT: ${{ needs.build.result }}
  #       run: |
  #         [[ "${RESULT}" == success ]]
